config/routes.rb
Rails.application.routes.draw do

  root 'books#index'
  resources :publishers, :authors, :categories, :books
  get '/about', to: 'about#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  belongs_to :author
  belongs_to :publisher
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  validates :name, presence: true, length: {minimum: 3}
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books

  validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = 'About Us'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def new
    @page_title = 'Add New Author'
    @author = Author.new
  end

  def show
  end

  def edit
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to authors_path, notice: 'Author created'
    else
      render 'new'
    end
  end

  def update
    @author.update(author_params)
    redirect_to authors_path, notice: 'Author updated'
  end

  def destroy
    @author.destroy
    redirect_to authors_path, notice: 'Author removed'
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
    @categories = Category.all
  end

  def new
    @page_title = 'Add Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def show
    @categories = Category.all
  end

  def edit
  end

  def create
    @book= Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: 'Book added'
    else
      render 'new'
    end
  end

  def update
    @book.update(book_params)
    redirect_to books_path, notice: 'Book updated'
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: 'Book removed'
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(
      :title,
      :category_id,
      :author_id,
      :publisher_id,
      :isbn,
      :price,
      :buy,
      :format,
      :excerpt,
      :pages,
      :year,
      :coverpath
    )
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @page_title = 'Add New Category'
    @category = Category.new
  end

  def show
    @categories = Category.all
    @books = @category.books
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category created'
    else
      render 'new'
    end
  end

  def update
    @category.update(category_params)
    redirect_to categories_path, notice: 'Category updated'
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: 'Category removed'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  def index
    @publishers = Publisher.all
  end

  def new
    @page_title = 'Add New Publisher'
    @publisher = Publisher.new
  end

  def show
  end

  def edit
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      redirect_to publishers_path, notice: 'Publisher created'
    else
      render 'new'
    end
  end

  def update
    @publisher.update(publisher_params)
    redirect_to publishers_path, notice: 'Publisher updated'
  end

  def destroy
    @publisher.destroy
    redirect_to publishers_path, notice: 'Publisher removed'
  end

  private

  def set_publisher
    @publisher = Publisher.find(params[:id])
  end

  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at euismod dolor. Phasellus facilisis malesuada dictum. Ut dignissim id ipsum eu hendrerit. Donec interdum purus consequat erat porta egestas. Morbi at felis non felis ultricies sagittis. Cras efficitur lacinia risus at blandit. Nullam dolor ante, efficitur non arcu eget, pellentesque varius ante.

  Nullam varius massa eros, eu vehicula diam ornare id. Ut enim urna, aliquam eget magna vitae, congue auctor est. Quisque nec elit id felis lobortis posuere. Pellentesque laoreet in nunc tincidunt tristique. Curabitur maximus et risus nec dignissim. In hac habitasse platea dictumst. Phasellus nunc arcu, maximus ut nulla non, pellentesque euismod massa.

  Integer et tincidunt ipsum. Sed odio leo, pretium et dapibus eu, iaculis vestibulum quam. Phasellus odio diam, porttitor rutrum suscipit congue, placerat eget lectus. Sed venenatis dui in quam interdum suscipit. Duis mattis luctus congue. Etiam vitae commodo dolor. Nullam in tempor enim. Nam vitae elit quis diam bibendum dapibus suscipit id ante. Suspendisse suscipit sed felis vitae tincidunt. Mauris luctus, enim sed convallis tristique, tortor arcu maximus urna, venenatis vehicula ex magna non libero. Donec porttitor eu sapien in posuere. Pellentesque bibendum libero vitae nunc egestas, commodo ornare diam congue. Aliquam imperdiet ullamcorper placerat.

  Suspendisse faucibus aliquet leo. Integer porttitor turpis nunc, at accumsan sapien gravida sit amet. Sed pellentesque mollis sapien. Fusce dictum ultrices elit, porta porttitor lectus vehicula eu. Nulla vitae sem sapien. Morbi porta dignissim justo, ut posuere ligula iaculis id. Maecenas et ultricies massa, eu vulputate neque. Sed neque risus, molestie ac scelerisque at, aliquam eget enim. Pellentesque sagittis ipsum neque, sed ornare sapien dignissim eget. Vestibulum ut fermentum leo. Donec rhoncus pellentesque arcu et eleifend. Praesent at magna est. Aenean sagittis sem id velit imperdiet tempus. Donec ultricies, orci ac rhoncus sollicitudin, tortor ipsum convallis dui, consectetur pellentesque lorem orci ac felis.

  Praesent vel erat sed est feugiat gravida vestibulum id lorem. Etiam ipsum felis, pulvinar a mi porta, luctus ultricies tortor. Sed eu risus purus. Ut volutpat leo vitae nisi congue, tincidunt aliquet nibh viverra. Integer tortor magna, semper vitae ante a, cursus maximus orci. Proin vitae sodales augue. Duis at aliquam libero, ac volutpat nibh.

  Vestibulum dictum, lectus vel lacinia tempus, justo justo cursus ante, nec congue est enim at erat. Donec in fermentum tellus. Aenean bibendum porttitor risus non vulputate. Etiam id suscipit nisl. Proin scelerisque quam lectus, condimentum euismod neque consectetur sit amet. Nunc aliquam laoreet lorem, ac mollis diam gravida et. Maecenas vitae volutpat erat, at consequat quam. Aliquam erat volutpat. Aenean sed condimentum lorem. Morbi in nulla et tortor congue sollicitudin in a felis. Quisque at elit at nisi ultrices vulputate et id odio. Mauris facilisis blandit interdum. Sed dictum, felis in convallis cursus, lorem enim viverra ex, at pulvinar nibh dui at urna. Vestibulum at eleifend nunc. Fusce lacinia eleifend mi, nec porta felis vestibulum non.

  Suspendisse sollicitudin dui non erat placerat luctus. Integer dictum, ante condimentum ornare consectetur, risus sem egestas est, non imperdiet quam velit et risus. Aliquam sem dui, facilisis vel leo in, maximus sagittis elit. Vivamus erat orci, tempus sit amet augue a, posuere porta sapien. Aenean ligula augue, condimentum ut lacus ut, porta fringilla leo. Integer pretium ipsum sit amet placerat suscipit. Sed vehicula ex in magna egestas, at aliquet velit tincidunt.

  Mauris sit amet eleifend purus. Sed dictum ultrices orci sit amet varius. Phasellus convallis turpis sed lobortis finibus. Sed consectetur non nisi eget dapibus. Curabitur ac orci a nibh mollis accumsan. Suspendisse ac odio tortor. Etiam sit amet vulputate magna, eget porttitor quam. Integer massa est, scelerisque sit amet egestas vel, egestas ultricies lectus.

  Morbi dolor erat, dignissim a leo eget, finibus feugiat elit. Quisque metus est, aliquam hendrerit sagittis in, pretium a libero. Nullam facilisis fringilla ante. Integer vitae magna dignissim, rutrum elit et, feugiat purus. Cras in pellentesque magna. Suspendisse mi lectus, condimentum at dignissim non, placerat sed arcu. Quisque aliquet augue non feugiat porttitor. Praesent quis nulla ante. Nullam pulvinar neque ac eros scelerisque facilisis. Proin vitae erat lacinia, tempus arcu vel, volutpat elit. Nam euismod, metus vel ullamcorper congue, odio augue congue nulla, porta maximus augue leo id orci. Maecenas dignissim quam felis, eu ultricies nisi dictum in.

  Nullam eu pharetra quam, ac fringilla diam. Quisque mattis ex et nulla sodales, vel aliquam elit efficitur. Donec tincidunt iaculis ligula et venenatis. Ut malesuada ante id purus pellentesque, nec commodo nisl iaculis. Nulla at blandit urna. Etiam ornare ut ante eu viverra. Praesent placerat condimentum tincidunt. Fusce ex ex, vulputate ac hendrerit a, luctus id ante. Curabitur viverra rutrum odio, in gravida arcu commodo vel. Nam convallis placerat nisi, nec tempus ante porta ac. Aenean accumsan aliquam massa nec ultrices. Curabitur ultricies massa et est laoreet varius. Fusce efficitur finibus elementum. Etiam id accumsan mauris. </p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h2>Edit Author</h2>

<%= form_for @author do |f| %>

  <!--Check for errors-->
  <% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |msg| %>
      <!--Show errors-->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control', required: true %>
  </div>
  <div class="mt-2">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', authors_path, class: 'btn btn-default', required: true %>
  </div>
<% end %>

app/views/authors/index.html.erb
<h2>Authors</h2>

<table class="table table-striped">
  <tr>
    <th>Author Name</th>
    <th>Actions</th>
  </tr>
  <% @authors.each do |author| %>
    <tr>
      <td><%= author.first_name + ' ' + author.last_name %></td>
      <td>
        <%= link_to 'Edit', edit_author_path(author.id) %> |
        <%= link_to 'Delete', author_path(author), method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/authors/new.html.erb
<h2>Add New Author</h2>

<%= form_for @author do |f| %>

  <!--Check for errors-->
  <% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |msg| %>
      <!--Show errors-->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control', required: true %>
  </div>
  <div class="mt-2">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', authors_path, class: 'btn btn-default', required: true %>
  </div>
<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h2>Edit New Book</h2>

<%= form_for @book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :isbn %>
    <%= f.text_field :isbn, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :category %>
    <%= f.select :category_id, Category.all.map {|x| [x.name, x.id]}, {include_blank: 'Select One'},  class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :author %>
    <%= f.select :author_id, Author.all.map {|x| [x.first_name + ' ' + x.last_name, x.id]}, {include_blank: 'Select One'},  class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :publisher %>
    <%= f.select :publisher_id, Publisher.all.map {|x| [x.name, x.id]}, {include_blank: 'Select One'},  class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :format %>
    <%= f.text_field :format, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :year %>
    <%= f.text_field :year, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :coverpath %>
    <%= f.text_field :coverpath, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :excerpt %>
    <%= f.text_area :excerpt, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :pages %>
    <%= f.number_field :pages, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :buy %>
    <%= f.text_field :buy, class: 'form-control', required: true %>
  </div>
  <div class="mt-2">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', books_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/books/index.html.erb
<div id="books-index" class="books-index">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-md-4 col-sm-6">
        <div class="card text-dark bg-light mb-3" style="max-width: 18rem;">
          <div class="card-header">
            <h5><%= book.title %></h5>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= image_tag(book.coverpath) %>
            </h5>
            <p class="card-text">
              <%= link_to 'Read More', book_path(book), class: 'btn btn-primary' %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<h2>Add New Book</h2>

<%= form_for @book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :isbn %>
    <%= f.text_field :isbn, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :category %>
    <%= f.select :category_id, Category.all.map {|x| [x.name, x.id]}, {include_blank: 'Select One'},  class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :author %>
    <%= f.select :author_id, Author.all.map {|x| [x.first_name + ' ' + x.last_name, x.id]}, {include_blank: 'Select One'},  class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :publisher %>
    <%= f.select :publisher_id, Publisher.all.map {|x| [x.name, x.id]}, {include_blank: 'Select One'},  class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :format %>
    <%= f.text_field :format, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :year %>
    <%= f.text_field :year, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :coverpath %>
    <%= f.text_field :coverpath, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :excerpt %>
    <%= f.text_area :excerpt, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :pages %>
    <%= f.number_field :pages, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control', required: true %>
  </div>
  <div class="form-group mt-2">
    <%= f.label :buy %>
    <%= f.text_field :buy, class: 'form-control', required: true %>
  </div>
  <div class="mt-2">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', books_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/books/show.html.erb
<div id="books-show" class="books-show">
  <h2><%= @book.title %></h2>
  <div class="books-show-left">
    <%= image_tag(@book.coverpath) %>
  </div>
  <div class="books-show-right">
    <h3>Book info:</h3>
    <ul>
      <li><strong>Category: </strong><%= @book.category.name %></li>
      <li><strong>Author: </strong><%= @book.author.first_name + ' ' + @book.author.last_name %></li>
      <li><strong>Publisher: </strong><%= @book.publisher.name %></li>
      <li><strong>Year: </strong><%= @book.year %></li>
      <li><strong>ISBN: </strong><%= @book.isbn %></li>
      <li><strong>Format: </strong><%= @book.format %></li>
      <li><strong>Pages: </strong><%= @book.pages %></li>
    </ul>
    <%= link_to 'Buy for ' + @book.price, @book.buy, class: 'btn btn-success', target: '_blank' %>
  </div>
  <div class="clearfix"></div>
  <div class="mt-5">
    <h4>Excerpt</h4>
    <p>
      <%= @book.excerpt %>
    </p>
  </div>
  <h4>Admin Functions</h4>
  <%= link_to 'Edit', edit_book_path(@book.id) %> |
  <%= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>

  <!--Check for errors-->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <!--Show errors-->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>
  <div class="mt-2">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', categories_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<table class="table table-striped">
  <tr>
    <th>Category Name</th>
    <th>Actions</th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td>
        <%= link_to 'Edit', edit_category_path(category.id) %> |
        <%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for @category do |f| %>

  <!--Check for errors-->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <!--Show errors-->
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>
  <div class="mt-2">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', categories_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<div class="row">
  <% @books.each do |book| %>
    <div class="col-md-4 col-sm-6">
      <div class="card text-dark bg-light mb-3" style="max-width: 18rem;">
        <div class="card-header">
          <h5><%= book.title %></h5>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <%= image_tag(book.coverpath) %>
          </h5>
          <p class="card-text">
            <%= link_to 'Read More', book_path(book), class: 'btn btn-primary' %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/partials/_header.html.erb
<header>
  <div class="container">
    <h1>The Bookstore <small class="h4"><%= @page_title ? @page_title : 'Welcome' %></small></h1>
  </div>
</header>

app/views/partials/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <!--<a class="navbar-brand" href="#">Navbar</a>-->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: "nav-link #{params[:controller] == 'books' ? 'active' : ''}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, class: "nav-link #{params[:controller] == 'about' ? 'active' : ''}" %>
          </li>
        </ul>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 to-right">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Add New
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li> <%= link_to 'Book', new_book_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'Category', new_category_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'Author', new_author_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'Publisher', new_publisher_path, class: 'dropdown-item' %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Manage
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'Categories', categories_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'Authors', authors_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'Publishers', publishers_path, class: 'dropdown-item' %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
  <div class="card border-dark mb-3" style="max-width: 18rem;">
    <div class="card-header">
      <h3>Location Info</h3>
    </div>
    <div class="card-body text-dark">
      <h5 class="card-title">The bookstore</h5>
      <p class="card-text">
        499 Massachusetts Ave, Unit 2 <br>
        Boston, MA 02110 <br>
        Phone: (617) 555-5555 <br>
        Email: support@thebookstore.com
      </p>
    </div>
  </div>
<% end %>

<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
  <ul class="list-group">
    <% @categories.each do |category| %>
      <li class="list-group-item"><%= link_to category.name, category_path(category.id), class: 'text-decoration-none text-dark' %></li>
    <% end %>
  </ul>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/index.html.erb
<h2>Publishers</h2>

<table class="table table-striped">
  <tr>
    <th>Publisher Name</th>
    <th>Actions</th>
  </tr>
  <% @publishers.each do |publisher| %>
    <tr>
      <td><%= publisher.name %></td>
      <td>
        <%= link_to 'Edit', edit_publisher_path(publisher.id) %> |
        <%= link_to 'Delete', publisher_path(publisher), method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>